"""TopoPyScale 2.0 CLI."""

from pathlib import Path
from typing import Optional

import numpy as np
import typer

from topopyscale2.cli._app import app, console
from topopyscale2.outputs.base import with_cf_metadata

# Template config for new simulations
_CONFIG_TEMPLATE = '''\
# TPS2 Configuration
# Generated by: tps2 init
# Documentation: https://github.com/joelfiddes/tps2

# =============================================================================
# Domain Definition
# =============================================================================
domain:
  # Bounding box [west, south, east, north] in EPSG:4326
  bbox: [7.5, 46.0, 7.7, 46.2]

  # DEM source: glo_90 (Copernicus 90m), glo_30 (30m), srtm_v3, nasadem
  dem_source: glo_90

  # Spatial mode: clusters (TopoSUB-style) or polygons (HRU-style)
  spatial_mode: clusters

  # Horizon angle computation (for sky view factor)
  horizon_n_directions: 8       # Azimuth directions (8 = every 45°)
  horizon_max_distance_m: 3000  # Max search distance in meters

  # Target CRS for processing (default: UTM auto-detected)
  # crs: EPSG:32632

# =============================================================================
# Input Data
# =============================================================================
inputs:
  # Primary NWP source
  primary: era5

  # Download backend: google (Google ARCO-ERA5, no account), cds (needs a CDS API key),
  # s3zarr, openmeteo, or local (a local ERA5 Zarr store: also set cache_path)
  backend: google

  # Time range [start, end] in YYYY-MM-DD format
  time_range: ["2023-06-01", "2023-06-03"]

  # Pressure levels for vertical interpolation
  pressure_levels: [500, 600, 700, 750, 800, 850, 900, 950]

  # Cache directory for downloaded data (relative to this config file)
  cache_dir: ./forcing_cache

# =============================================================================
# Clustering (when spatial_mode: clusters)
# =============================================================================
clustering:
  method: kmeans
  n_clusters: 50
  features: [elevation, slope, aspect, svf]

# =============================================================================
# Downscaling Physics
# =============================================================================
downscaling:
  # full: temperature, humidity and wind from the pressure levels at each unit's elevation.
  # simple: surface fields only, temperature moved with a fixed lapse_rate (K/m).
  mode: full
  lapse_rate: 0.0065

  # Precipitation amount: none = each unit gets its grid cell's amount (default).
  # elevation_gradient scales it with elevation (precip_gradient, per metre): opt in.
  precipitation: none
  precip_gradient: 0.0003

  # Rain/snow split: wet_bulb (default) or air_temperature, with a linear ramp between
  # the two thresholds (degC) and all rain above t_air_max_c air temperature.
  phase_method: wet_bulb
  t_snow_threshold_c: -0.5
  t_rain_threshold_c: 2.5
  t_air_max_c: 4.0

  # Wind: log_profile, or winstral (adds terrain exposure, Sx).
  wind_config:
    method: log_profile

# =============================================================================
# Execution
# =============================================================================
execution:
  # Kernel backend: rust (fast), python (reference), jax (differentiable)
  kernel_backend: rust

  # Parallel workers (0 = auto-detect)
  n_workers: 0

# =============================================================================
# Output
# =============================================================================
output:
  # Output format: zarr, netcdf, fsm, smet, csv
  format: zarr

  # Output directory (relative to this config file)
  directory: ./output

  # Variables to output (empty = all)
  variables: []

# =============================================================================
# Storage & Caching
# =============================================================================
storage:
  # DEM cache directory (relative to this config file)
  dem_cache: ./dem_cache
'''

# Template run script for new simulations
_RUN_TEMPLATE = '''\
#!/bin/bash
# ==============================================================================
# TPS2 Simulation Run Script
# Generated by: tps2 init
#
# This script controls and documents the simulation run.
# Edit this file to customize execution options.
# ==============================================================================

set -e  # Exit on error

# Configuration
CONFIG="config.yaml"
LOG_FILE="simulation.log"

# Environment (uncomment and edit if needed)
# export PYTHONUNBUFFERED=1
# export PATH="/path/to/conda/envs/tps2/bin:$PATH"

# Run options (uncomment as needed)
# --kernel python|rust|jax: Select compute backend

echo "Starting TPS2 simulation: $(basename $(pwd))"
echo "Config: $CONFIG"
echo "Log: $LOG_FILE"
echo "Started: $(date)"

# Run the simulation (dashboard is created automatically)
tps2 run --config "$CONFIG" 2>&1 | tee "$LOG_FILE"

echo ""
echo "Finished: $(date)"
echo "Output: output/"
'''


@app.command()
def init(
    path: Path = typer.Argument(..., help="Path for new simulation directory"),
    bbox: Optional[str] = typer.Option(
        None, "--bbox", "-b",
        help="Bounding box as 'west,south,east,north' (e.g., '7.5,46.0,7.7,46.2')"
    ),
    time_range: Optional[str] = typer.Option(
        None, "--time", "-t",
        help="Time range as 'start,end' (e.g., '2023-06-01,2023-06-03')"
    ),
    force: bool = typer.Option(
        False, "--force", "-f",
        help="Overwrite existing directory"
    ),
):
    """Initialize a new simulation directory with template config.

    Creates the directory structure:

        <path>/
        ├── config.yaml      # Configuration file (edit this)
        ├── run.sh           # Run script (customizable)
        ├── dem_cache/       # DEM data cached here
        ├── forcing_cache/   # ERA5 data cached here
        └── output/          # Downscaled output written here

    After init, edit config.yaml to set your domain, time range, and options,
    then run: ./run.sh (or: tps2 run --config <path>/config.yaml)

    Examples:

        tps2 init ~/sim/alps_summer2023

        tps2 init ./my_run --bbox 7.5,46.0,7.7,46.2 --time 2023-06-01,2023-06-30
    """
    path = path.expanduser().resolve()

    # Check if directory exists
    if path.exists():
        if not force:
            console.print(f"[red]Error: Directory {path} already exists.[/red]")
            console.print("[yellow]Use --force to overwrite.[/yellow]")
            raise typer.Exit(1)
        else:
            console.print(f"[yellow]Overwriting existing directory {path}[/yellow]")

    # Create directory structure
    console.print(f"[bold]Initializing simulation: {path}[/bold]")

    subdirs = ["dem_cache", "forcing_cache", "output"]
    for subdir in subdirs:
        (path / subdir).mkdir(parents=True, exist_ok=True)
        console.print(f"  Created {subdir}/")

    # Prepare config content
    config_content = _CONFIG_TEMPLATE

    # Substitute bbox if provided
    if bbox:
        try:
            parts = [float(x.strip()) for x in bbox.split(",")]
            if len(parts) != 4:
                raise ValueError("Need exactly 4 values")
            bbox_str = f"[{parts[0]}, {parts[1]}, {parts[2]}, {parts[3]}]"
            config_content = config_content.replace(
                "bbox: [7.5, 46.0, 7.7, 46.2]",
                f"bbox: {bbox_str}"
            )
            console.print(f"  Bbox: {bbox_str}")
        except ValueError as e:
            console.print(f"[yellow]Warning: Invalid bbox format, using default. ({e})[/yellow]")

    # Substitute time range if provided
    if time_range:
        try:
            parts = [x.strip() for x in time_range.split(",")]
            if len(parts) != 2:
                raise ValueError("Need exactly 2 dates")
            time_str = f'["{parts[0]}", "{parts[1]}"]'
            config_content = config_content.replace(
                'time_range: ["2023-06-01", "2023-06-03"]',
                f"time_range: {time_str}"
            )
            console.print(f"  Time range: {time_str}")
        except ValueError as e:
            console.print(f"[yellow]Warning: Invalid time format, using default. ({e})[/yellow]")

    # Write config file
    config_path = path / "config.yaml"
    config_path.write_text(config_content)
    console.print("  Created config.yaml")

    # Write run script
    run_path = path / "run.sh"
    run_path.write_text(_RUN_TEMPLATE)
    run_path.chmod(0o755)  # Make executable
    console.print("  Created run.sh")

    # Summary
    console.print("\n[green]Simulation initialized![/green]")
    console.print("\nNext steps:")
    console.print(f"  1. Edit the config:  [cyan]vim {config_path}[/cyan]")
    console.print(f"  2. Run the pipeline: [cyan]cd {path} && ./run.sh[/cyan]")
    console.print(f"     (or directly:     [cyan]tps2 run --config {config_path}[/cyan])")


@app.command()
def setup(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
):
    """Set up domain: DEM acquisition, terrain processing, clustering."""
    from topopyscale2.domain import Domain

    console.print(f"[bold]Setting up domain from {config}[/bold]")
    domain = Domain.from_config(config)
    domain.setup()
    console.print(domain.info())
    console.print("[green]Domain setup complete.[/green]")


@app.command(name="fetch-forcing")
def fetch_forcing(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
    primary: Optional[str] = typer.Option(
        None, "--primary", "-p",
        help="NWP source (era5|ifs). Overrides config if set."
    ),
):
    """Fetch NWP forcing data (ERA5 or IFS)."""
    from topopyscale2.config.schema import TPS2Config
    from topopyscale2.domain import Domain

    console.print(f"[bold]Fetching forcing data from {config}[/bold]")
    cfg = TPS2Config.from_yaml(config)

    if primary:
        cfg.inputs.primary = primary

    console.print(f"  Source: {cfg.inputs.primary}")
    domain = Domain(cfg)
    domain.fetch_forcing()
    console.print("[green]Forcing data downloaded.[/green]")


def _live_dashboard_updater():
    """``update_live_dashboard`` when the dashboard module ships, else a no-op.

    The live status page is a SnowMapper product; a core-only release has none, and
    run progress is still written by ``_write_progress`` (progress.json).
    """
    try:
        from topopyscale2.outputs.dashboard import update_live_dashboard
    except ImportError:
        return lambda *args, **kwargs: None
    return update_live_dashboard


def _write_progress(sim_dir: Path, steps: list[dict]) -> None:
    """Write progress state to JSON for dashboard consumption."""
    import json
    from datetime import datetime
    (sim_dir / "progress.json").write_text(json.dumps({
        "timestamp": datetime.now().isoformat(),
        "steps": steps,
    }))


@app.command()
def run(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
    backend: Optional[str] = typer.Option(
        None, "--backend", "-b",
        help="Kernel backend (python|rust|jax). Overrides config if set."
    ),
    primary: Optional[str] = typer.Option(
        None, "--primary", "-p",
        help="NWP source (era5|ifs). Overrides config if set."
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be done without running."
    ),
    raster_output: bool = typer.Option(
        False, "--raster", help="Also output gridded raster (time, y, x)."
    ),
    geotiff_var: Optional[str] = typer.Option(
        None, "--geotiff",
        help="Variable to export as GeoTIFF series (e.g., temperature)."
    ),
):
    """Run full pipeline: setup -> fetch -> downscale -> write output.

    Supports Phase 2 features:
    - Polygon mode (HRU generation) when spatial_mode: polygons
    - Winstral wind correction when wind method: winstral
    - Snow redistribution when redistribution.wind_transport or avalanche enabled
    - Multi-NWP source blending when sources configured
    """
    import logging
    import os
    import time

    import numpy as np
    import pandas as pd
    import xarray as xr

    from topopyscale2.config.schema import TPS2Config
    from topopyscale2.core.downscale import Downscaler
    from topopyscale2.domain import Domain
    from topopyscale2.inputs.derived import (
        compute_clearness_index,
        compute_solar_elevation,
    )
    update_live_dashboard = _live_dashboard_updater()

    # Set up logging to both console and file
    log_file = config.parent / "simulation.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, mode="w"),
            logging.StreamHandler(),
        ],
    )
    log = logging.getLogger(__name__)
    log.info("Logging to %s", log_file)

    # Change to config directory so relative paths work
    config = config.resolve()
    config_dir = config.parent
    os.chdir(config_dir)

    console.print(f"[bold]TPS2 Pipeline: {config.name}[/bold]")
    console.print(f"Working directory: {config_dir}")

    cfg = TPS2Config.from_yaml(config)

    # Override backend if specified on command line
    kernel_backend = backend or cfg.execution.kernel_backend

    # Override NWP source if specified on command line
    if primary:
        cfg.inputs.primary = primary

    # Display configuration summary
    console.print("\n[bold]Configuration:[/bold]")
    console.print(f"  Bbox: {cfg.domain.bbox}")
    console.print(f"  Time range: {cfg.inputs.time_range}")
    console.print(f"  NWP source: {cfg.inputs.primary}")
    console.print(f"  Spatial mode: {cfg.domain.spatial_mode}")
    console.print(f"  Kernel backend: {kernel_backend}")

    # --- Preflight checks (always run before committing to pipeline) ---
    from topopyscale2.preflight import format_report, run_preflight

    report = run_preflight(cfg, skip_disk=False)

    # Print compact preflight summary
    status_icons = {"pass": "\u2713", "warn": "\u26a0", "fail": "\u2717"}
    status_styles = {"pass": "green", "warn": "yellow", "fail": "red"}
    console.print("\n[bold]Preflight Checks[/bold]")
    for c in report.checks:
        if c.status != "pass":
            icon = status_icons[c.status]
            style = status_styles[c.status]
            console.print(f"  [{style}]{icon}[/{style}] {c.message}")
    console.print(
        f"  {report.n_pass} passed, {report.n_warn} warning(s), {report.n_fail} error(s)"
    )

    if report.n_fail > 0:
        console.print("\n[red bold]Preflight failed — fix errors above before running.[/red bold]")
        console.print("[dim]Run 'tps2 preflight -c config.yaml' for full report.[/dim]")
        raise typer.Exit(1)

    if dry_run:
        # In dry-run mode, show full preflight report and estimates
        console.print()
        console.print(format_report(report, config.name))
        console.print("\n[yellow]Dry run mode - no actions taken.[/yellow]")
        return

    # Create live dashboard at start
    update_live_dashboard(config_dir, status="Running", step="Initializing...")
    console.print(f"  Dashboard: {config_dir / 'dashboard.html'}")

    # Initialize progress tracking
    progress_steps = [
        {"name": "Domain setup", "status": "pending", "completed": 0, "total": 4, "detail": "sub-steps"},
        {"name": "Fetch forcing", "status": "pending", "completed": 0, "total": 1},
        {"name": "Derived quantities", "status": "pending", "completed": 0, "total": 2, "detail": "quantities"},
        {"name": "Downscaling", "status": "pending", "completed": 0, "total": 1, "detail": "units"},
        {"name": "Write output", "status": "pending", "completed": 0, "total": 1},
    ]
    _write_progress(config_dir, progress_steps)

    domain = Domain(cfg)
    start_time = time.time()

    # === 1. Setup domain ===
    console.print("\n[bold]Step 1: Domain Setup[/bold]")
    update_live_dashboard(config_dir, status="Running", step="Step 1: Domain Setup")
    progress_steps[0]["status"] = "active"
    _write_progress(config_dir, progress_steps)

    def _setup_callback(step, total, desc):
        progress_steps[0]["completed"] = step
        progress_steps[0]["total"] = total
        progress_steps[0]["detail"] = desc
        _write_progress(config_dir, progress_steps)

    domain.setup(progress_callback=_setup_callback)
    progress_steps[0]["status"] = "complete"
    if domain.units is not None:
        console.print(f"  Units: {len(domain.units)}")
    if domain.dem_data is not None and "elevation" in domain.dem_data:
        elev = domain.dem_data["elevation"]
        console.print(f"  DEM: {elev.shape[0]}x{elev.shape[1]} pixels")
        console.print(f"  Elevation: {float(elev.min()):.0f} - {float(elev.max()):.0f} m")

    # === 2. Estimate forcing memory before loading ===
    # Compute expected forcing size to decide single-pass vs chunked processing
    from topopyscale2.inputs.units import convert_era5_pressure, convert_era5_surface

    tr = cfg.inputs.time_range
    if tr and len(tr) == 2:
        _tr_start = pd.Timestamp(tr[0])
        _tr_end = pd.Timestamp(tr[1])
        _est_days = (_tr_end - _tr_start).days + 1
    else:
        _est_days = 1
    _hpd = {"1H": 24, "3H": 8, "6H": 4}.get(cfg.inputs.time_resolution, 24)
    _est_timesteps = _est_days * _hpd
    if cfg.domain.bbox is not None:
        _est_n_lat = int((cfg.domain.bbox[3] - cfg.domain.bbox[1]) / 0.25) + 1
        _est_n_lon = int((cfg.domain.bbox[2] - cfg.domain.bbox[0]) / 0.25) + 1
    else:
        # Sparse points mode — estimate small grid per point group
        _est_n_lat = 5
        _est_n_lon = 5
    _est_n_levels = len(cfg.inputs.pressure_levels)
    _n_surf_vars_est = 10
    _n_plev_vars_est = 6
    _forcing_bytes_est = (_est_timesteps * _est_n_lat * _est_n_lon * 4 *
                          (_n_surf_vars_est + _n_plev_vars_est * _est_n_levels))

    # Also estimate output memory: n_units × n_timesteps × n_output_vars × 8 bytes
    _n_units = cfg.clustering.n_clusters if hasattr(cfg.clustering, 'n_clusters') else 100
    _n_output_vars = 12  # temperature, pressure, humidity×2, precip×3, radiation×3, wind×2
    _output_bytes_est = _est_timesteps * _n_units * _n_output_vars * 8
    _total_bytes_est = _forcing_bytes_est + _output_bytes_est

    import os
    if os.environ.get("TPS2_MAX_RAM_GB"):
        _available_ram = int(float(os.environ["TPS2_MAX_RAM_GB"]) * 1024**3)
    else:
        try:
            import psutil
            _available_ram = int(psutil.virtual_memory().total * 0.7)
        except ImportError:
            _available_ram = 24 * 1024**3  # conservative 24 GB default

    _needs_temporal_chunking = _total_bytes_est > _available_ram

    if _needs_temporal_chunking:
        # Compute chunk size in years
        _est_years = max(1, _est_days / 365.25)
        _bytes_per_year = _total_bytes_est / _est_years
        _chunk_years = max(1, int(_available_ram / _bytes_per_year))

        # Build year list from time range
        _year_start = _tr_start.year
        _year_end = _tr_end.year
        _all_years = list(range(_year_start, _year_end + 1))
        _year_chunks = []
        for i in range(0, len(_all_years), _chunk_years):
            _year_chunks.append(_all_years[i:i + _chunk_years])
        _n_chunks = len(_year_chunks)

        console.print("\n[bold]Step 2: Fetch & Downscale (chunked)[/bold]")
        console.print(f"  [yellow]Memory ~{_total_bytes_est / 1e9:.1f} GB "
                      f"(forcing {_forcing_bytes_est / 1e9:.1f} + output {_output_bytes_est / 1e9:.1f}) "
                      f"exceeds ~{_available_ram / 1e9:.0f} GB RAM limit — "
                      f"processing in {_n_chunks} chunk(s) of {_chunk_years} year(s)[/yellow]")
        update_live_dashboard(config_dir, status="Running", step="Step 2: Chunked processing")
        progress_steps[1]["status"] = "active"
        _write_progress(config_dir, progress_steps)

        # Set up downscaler once (reused across chunks)
        n_workers = cfg.execution.n_workers if hasattr(cfg, "execution") else 1
        precip_grad = (cfg.downscaling.precip_gradient
            if cfg.downscaling.precipitation == "elevation_gradient" else 0.0)
        downscaler = Downscaler(
            backend=kernel_backend, n_workers=n_workers, mode=cfg.downscaling.mode,
            precip_gradient=precip_grad,
            phase_method=cfg.downscaling.phase_method,
            t_snow=cfg.downscaling.t_snow_threshold_c + 273.15,
            t_rain=cfg.downscaling.t_rain_threshold_c + 273.15,
            t_air_max=cfg.downscaling.t_air_max_c + 273.15,
            lapse_rate=cfg.downscaling.lapse_rate,
        )

        n_units = len(domain.units) if domain.units is not None else 1
        progress_steps[3]["status"] = "active"
        progress_steps[3]["total"] = n_units * _n_chunks
        _write_progress(config_dir, progress_steps)

        _last_progress_write = [0.0]
        def _ds_progress_callback(done, total):
            now = time.time()
            if done == total or now - _last_progress_write[0] > 1.0:
                progress_steps[3]["completed"] = _chunk_offset + done
                progress_steps[3]["total"] = n_units * _n_chunks
                _write_progress(config_dir, progress_steps)
                _last_progress_write[0] = now

        output_dir = Path(cfg.output.directory)
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "forcing.zarr" if cfg.output.format == "zarr" else output_dir / "forcing.nc"
        first_chunk = True
        requested_outputs = cfg.output.variables

        ds_time_start = time.time()
        _chunk_offset = 0

        for ci, chunk_yrs in enumerate(_year_chunks):
            y_start, y_end = chunk_yrs[0], chunk_yrs[-1]
            console.print(f"\n  [bold]Chunk {ci + 1}/{_n_chunks}: {y_start}–{y_end}[/bold]")
            update_live_dashboard(config_dir, status="Running",
                                  step=f"Chunk {ci + 1}/{_n_chunks} ({y_start}–{y_end})")

            # Fetch forcing for this chunk's time range only
            chunk_time_range = [f"{y_start}-01-01", f"{y_end}-12-31"]
            domain.fetch_forcing(time_range=chunk_time_range)

            # Convert units
            ds_surf = convert_era5_surface(domain._ds_surface)
            ds_plev = (convert_era5_pressure(domain._ds_pressure)
                       if domain._ds_pressure is not None else None)
            datasets_to_merge = [ds_surf]
            if ds_plev is not None:
                datasets_to_merge.append(ds_plev)
            chunk_forcing = xr.merge(datasets_to_merge)

            if "strd" not in chunk_forcing and all(v in chunk_forcing for v in ("t2m", "d2m", "ssrd")):
                from topopyscale2.inputs.derived import synthesize_longwave
                chunk_forcing["strd"] = synthesize_longwave(chunk_forcing)

            if ci == 0:
                console.print(f"    Variables: {list(chunk_forcing.data_vars)[:8]}...")

            console.print(f"    Timesteps: {len(chunk_forcing.time)}")

            # Resolve variable groups (only on first chunk)
            if ci == 0:
                from topopyscale2.core.downscale import resolve_groups
                surf_vars_avail = {v for v in chunk_forcing.data_vars
                                   if "level" not in chunk_forcing[v].dims}
                plev_vars_avail = {v for v in chunk_forcing.data_vars
                                   if "level" in chunk_forcing[v].dims}
                active_groups = resolve_groups(
                    surf_vars_avail, plev_vars_avail, requested_outputs, cfg.downscaling.mode,
                )
                console.print(f"    Active groups: {active_groups}")

            # Compute derived quantities for this chunk
            if "radiation" in active_groups:
                sol_elev = compute_solar_elevation(chunk_forcing)
                chunk_forcing["solar_elevation"] = sol_elev
                kt = compute_clearness_index(chunk_forcing)
                chunk_forcing["clearness_index"] = kt

            # Load into memory (only this chunk — should fit)
            chunk_forcing = chunk_forcing.load()

            # Downscale
            chunk_results = downscaler.process(
                domain.units, chunk_forcing, domain.dem_data,
                requested_outputs=requested_outputs or None,
                progress_callback=_ds_progress_callback,
            )

            # Write chunk to output
            if cfg.output.format == "zarr":
                for var in chunk_results.variables:
                    chunk_results[var].encoding.pop("chunks", None)
                if first_chunk:
                    with_cf_metadata(chunk_results).to_zarr(str(output_path), mode="w")
                    first_chunk = False
                else:
                    chunk_results.to_zarr(str(output_path), mode="a", append_dim="time")
            elif cfg.output.format == "netcdf":
                if first_chunk:
                    all_results = [chunk_results]
                    first_chunk = False
                else:
                    all_results.append(chunk_results)

            _chunk_offset += n_units
            console.print(f"    Written chunk {ci + 1}/{_n_chunks}")

            # Free memory
            del chunk_results, chunk_forcing, ds_surf, ds_plev, datasets_to_merge
            domain._ds_surface = None
            domain._ds_pressure = None
            import gc

            gc.collect()

        ds_elapsed = time.time() - ds_time_start

        if cfg.output.format == "netcdf":
            with_cf_metadata(xr.concat(all_results, dim="time")).to_netcdf(str(output_path))
            del all_results

        console.print(f"\n  Downscaled {n_units} units × {_n_chunks} chunks in {ds_elapsed:.1f}s")
        console.print(f"  Written: {output_path}")

        # Mark steps complete and skip to output summary
        progress_steps[1]["status"] = "complete"
        progress_steps[1]["completed"] = 1
        progress_steps[2]["status"] = "complete"
        progress_steps[2]["completed"] = 2
        progress_steps[3]["status"] = "complete"
        progress_steps[3]["completed"] = n_units * _n_chunks
        _write_progress(config_dir, progress_steps)

        results = None  # already written incrementally

    else:
        # === Standard single-pass mode (forcing fits in memory) ===

        # === 2. Fetch forcing ===
        console.print("\n[bold]Step 2: Fetch Forcing[/bold]")
        update_live_dashboard(config_dir, status="Running", step="Step 2: Fetch Forcing")
        progress_steps[1]["status"] = "active"
        _write_progress(config_dir, progress_steps)
        domain.fetch_forcing()
        progress_steps[1]["status"] = "complete"
        progress_steps[1]["completed"] = 1

        # Get raw datasets and apply unit conversion
        ds_surf_raw = domain._ds_surface
        ds_plev_raw = domain._ds_pressure

        ds_surf = convert_era5_surface(ds_surf_raw)
        ds_plev = convert_era5_pressure(ds_plev_raw) if ds_plev_raw is not None else None

        datasets_to_merge = [ds_surf]
        if ds_plev is not None:
            datasets_to_merge.append(ds_plev)
        forcing = xr.merge(datasets_to_merge)

        # Synthesize longwave if missing (e.g. forecast-only source)
        if "strd" not in forcing and all(v in forcing for v in ("t2m", "d2m", "ssrd")):
            from topopyscale2.inputs.derived import synthesize_longwave
            console.print("  Synthesizing strd from t2m/d2m/ssrd (Brutsaert + Konzelmann)")
            forcing["strd"] = synthesize_longwave(forcing)

        console.print(f"  Variables: {list(forcing.data_vars)[:8]}...")
        console.print(f"  Timesteps: {len(forcing.time)}")

        # === 3. Resolve variable groups and compute derived quantities ===
        console.print("\n[bold]Step 3: Derived Quantities[/bold]")
        update_live_dashboard(config_dir, status="Running", step="Step 3: Derived Quantities")
        progress_steps[2]["status"] = "active"
        _write_progress(config_dir, progress_steps)

        from topopyscale2.core.downscale import resolve_groups

        requested_outputs = cfg.output.variables
        surf_vars_avail = {v for v in forcing.data_vars
                           if "level" not in forcing[v].dims}
        plev_vars_avail = {v for v in forcing.data_vars
                           if "level" in forcing[v].dims}
        active_groups = resolve_groups(
            surf_vars_avail, plev_vars_avail, requested_outputs, cfg.downscaling.mode,
        )
        console.print(f"  Active groups: {active_groups}")
        if not active_groups:
            console.print("[yellow]Warning: No computation groups resolved from available inputs.[/yellow]")

        if "radiation" in active_groups:
            solar_elev = compute_solar_elevation(forcing)
            forcing["solar_elevation"] = solar_elev
            console.print(f"  Solar elevation: {float(solar_elev.min()):.1f} to {float(solar_elev.max()):.1f} deg")
            progress_steps[2]["completed"] = 1
            _write_progress(config_dir, progress_steps)

            kt = compute_clearness_index(forcing)
            forcing["clearness_index"] = kt
            console.print(f"  Clearness index: {float(kt.min()):.2f} to {float(kt.max()):.2f}")
            progress_steps[2]["completed"] = 2
        else:
            console.print("  Skipping solar/clearness (radiation group not active)")
            progress_steps[2]["completed"] = 2
        progress_steps[2]["status"] = "complete"
        _write_progress(config_dir, progress_steps)

        # === 4. Run downscaling ===
        console.print(f"\n[bold]Step 4: Downscaling ({kernel_backend})[/bold]")
        update_live_dashboard(config_dir, status="Running", step="Step 4: Downscaling")

        n_workers = cfg.execution.n_workers if hasattr(cfg, "execution") else 1
        precip_grad = (cfg.downscaling.precip_gradient
            if cfg.downscaling.precipitation == "elevation_gradient" else 0.0)
        downscaler = Downscaler(
            backend=kernel_backend, n_workers=n_workers, mode=cfg.downscaling.mode,
            precip_gradient=precip_grad,
            phase_method=cfg.downscaling.phase_method,
            t_snow=cfg.downscaling.t_snow_threshold_c + 273.15,
            t_rain=cfg.downscaling.t_rain_threshold_c + 273.15,
            t_air_max=cfg.downscaling.t_air_max_c + 273.15,
            lapse_rate=cfg.downscaling.lapse_rate,
        )

        n_units = len(domain.units) if domain.units is not None else 1
        progress_steps[3]["status"] = "active"
        progress_steps[3]["total"] = n_units
        _write_progress(config_dir, progress_steps)

        _last_progress_write = [0.0]
        def _ds_progress_callback(done, total):
            now = time.time()
            if done == total or now - _last_progress_write[0] > 1.0:
                progress_steps[3]["completed"] = done
                progress_steps[3]["total"] = total
                _write_progress(config_dir, progress_steps)
                _last_progress_write[0] = now

        output_dir = Path(cfg.output.directory)
        output_dir.mkdir(parents=True, exist_ok=True)

        ds_time = time.time()
        results = downscaler.process(
            domain.units, forcing, domain.dem_data,
            requested_outputs=requested_outputs or None,
            progress_callback=_ds_progress_callback,
        )
        ds_elapsed = time.time() - ds_time

    progress_steps[3]["status"] = "complete"
    progress_steps[3]["completed"] = n_units
    _write_progress(config_dir, progress_steps)

    if results is not None:
        console.print(f"  Downscaled {len(domain.units)} units in {ds_elapsed:.1f}s")
        console.print(f"  Output variables: {list(results.data_vars)}")

        # === 5. Output statistics ===
        console.print("\n[bold]Output Statistics:[/bold]")
        for var in ["temperature", "precipitation", "shortwave_direct", "longwave"]:
            if var in results:
                data = results[var].values
                console.print(f"  {var}: {np.nanmin(data):.1f} to {np.nanmax(data):.1f} (mean={np.nanmean(data):.2f})")

        # === 6. Write output ===
        console.print(f"\n[bold]Step 5: Write Output ({cfg.output.format})[/bold]")
        update_live_dashboard(config_dir, status="Running", step="Step 5: Write Output")
        progress_steps[4]["status"] = "active"
        _write_progress(config_dir, progress_steps)
        output_dir.mkdir(parents=True, exist_ok=True)

        if cfg.output.format == "zarr":
            output_path = output_dir / "forcing.zarr"
            with_cf_metadata(results).to_zarr(str(output_path), mode="w")
            console.print(f"  Written: {output_path}")
        elif cfg.output.format == "netcdf":
            output_path = output_dir / "forcing.nc"
            with_cf_metadata(results).to_netcdf(str(output_path))
            console.print(f"  Written: {output_path}")
        else:
            console.print(f"  [yellow]Output format '{cfg.output.format}' writer not yet implemented[/yellow]")

    # === 6b. Raster output (optional) ===
    if raster_output or geotiff_var:
        from topopyscale2.outputs.raster_mapper import RasterMapper

        console.print("\n[bold]Step 6: Raster Output[/bold]")

        try:
            mapper = RasterMapper.from_domain(domain)

            if raster_output:
                raster_path = output_dir / "forcing_raster.zarr"
                mapper.write_raster_dataset(results, raster_path, format="zarr")
                console.print(f"  Raster output: {raster_path}")

            if geotiff_var:
                if geotiff_var not in results:
                    console.print(f"  [yellow]Variable '{geotiff_var}' not in output, skipping GeoTIFF.[/yellow]")
                else:
                    geotiff_dir = output_dir / "geotiffs" / geotiff_var
                    paths = mapper.write_geotiff_series(results, geotiff_dir, geotiff_var)
                    console.print(f"  GeoTIFFs: {geotiff_dir}/ ({len(paths)} files)")

        except Exception as e:
            console.print(f"  [yellow]Raster output failed: {e}[/yellow]")
            log.warning("Raster output failed: %s", e)

    progress_steps[4]["status"] = "complete"
    progress_steps[4]["completed"] = 1
    _write_progress(config_dir, progress_steps)

    # === Summary ===
    total_time = time.time() - start_time
    console.print(f"\n[green]Pipeline complete in {total_time:.1f}s[/green]")

    # Clean up progress.json (mark all complete so dashboard shows final state)
    progress_file = config_dir / "progress.json"
    if progress_file.exists():
        progress_file.unlink()

    # Final dashboard update
    update_live_dashboard(config_dir, status="Complete", step=f"Finished in {total_time:.1f}s")


def _run_downscale_pipeline(
    domain,
    cfg,
    ds_surf_raw,
    ds_plev_raw,
    kernel_backend: str,
    config_dir: Path,
    progress_steps: list[dict],
    raster_output: bool = False,
    geotiff_var: str | None = None,
    skip_output: bool = False,
    label: str = "",
    derived_step: int = 2,
    downscale_step: int = 3,
    output_step: int = 4,
):
    """Shared downscaling pipeline: unit convert -> derived -> downscale -> output.

    Used by both ``run`` and ``forecast run`` to avoid code duplication.

    Parameters
    ----------
    skip_output : bool
        When True, skip output writing and raster steps — just return
        the downscaled xr.Dataset.
    label : str
        Label for console output (e.g. "ERA5", "Forecast").
    derived_step, downscale_step, output_step : int
        Indices into *progress_steps* for the derived-quantities,
        downscaling, and output-writing steps respectively.
    """
    import time

    import numpy as np
    import xarray as xr

    from topopyscale2.core.downscale import Downscaler, resolve_groups
    from topopyscale2.inputs.derived import (
        compute_clearness_index,
        compute_solar_elevation,
        synthesize_longwave,
    )
    from topopyscale2.inputs.units import convert_era5_pressure, convert_era5_surface
    update_live_dashboard = _live_dashboard_updater()

    prefix = f"[{label}] " if label else ""

    # Convert ERA5 units
    ds_surf = convert_era5_surface(ds_surf_raw)
    ds_plev = convert_era5_pressure(ds_plev_raw) if ds_plev_raw is not None else None

    datasets_to_merge = [ds_surf]
    if ds_plev is not None:
        datasets_to_merge.append(ds_plev)
    forcing = xr.merge(datasets_to_merge)

    # Synthesize longwave if missing (e.g. Open-Meteo IFS forecast)
    if "strd" not in forcing and all(v in forcing for v in ("t2m", "d2m", "ssrd")):
        console.print(f"  {prefix}Synthesizing strd from t2m/d2m/ssrd (Brutsaert + Konzelmann)")
        forcing["strd"] = synthesize_longwave(forcing)

    console.print(f"  {prefix}Variables: {list(forcing.data_vars)[:8]}...")
    console.print(f"  {prefix}Timesteps: {len(forcing.time)}")

    # === Derived quantities ===
    console.print(f"\n[bold]{prefix}Derived Quantities[/bold]")
    update_live_dashboard(config_dir, status="Running", step=f"{prefix}Derived Quantities")
    progress_steps[derived_step]["status"] = "active"
    _write_progress(config_dir, progress_steps)

    requested_outputs = cfg.output.variables
    surf_vars_avail = {v for v in forcing.data_vars if "level" not in forcing[v].dims}
    plev_vars_avail = {v for v in forcing.data_vars if "level" in forcing[v].dims}
    active_groups = resolve_groups(
        surf_vars_avail, plev_vars_avail, requested_outputs, cfg.downscaling.mode,
    )
    console.print(f"  Active groups: {active_groups}")

    if "radiation" in active_groups:
        solar_elev = compute_solar_elevation(forcing)
        forcing["solar_elevation"] = solar_elev
        console.print(f"  Solar elevation: {float(solar_elev.min()):.1f} to {float(solar_elev.max()):.1f} deg")
        progress_steps[derived_step]["completed"] = 1
        _write_progress(config_dir, progress_steps)

        kt = compute_clearness_index(forcing)
        forcing["clearness_index"] = kt
        console.print(f"  Clearness index: {float(kt.min()):.2f} to {float(kt.max()):.2f}")
        progress_steps[derived_step]["completed"] = 2
    else:
        console.print("  Skipping solar/clearness (radiation group not active)")
        progress_steps[derived_step]["completed"] = 2
    progress_steps[derived_step]["status"] = "complete"
    _write_progress(config_dir, progress_steps)

    # === Downscaling ===
    console.print(f"\n[bold]{prefix}Downscaling ({kernel_backend})[/bold]")
    update_live_dashboard(config_dir, status="Running", step=f"{prefix}Downscaling")

    n_workers = cfg.execution.n_workers if hasattr(cfg, "execution") else 1
    precip_grad = (cfg.downscaling.precip_gradient
        if cfg.downscaling.precipitation == "elevation_gradient" else 0.0)
    downscaler = Downscaler(
        backend=kernel_backend, n_workers=n_workers, mode=cfg.downscaling.mode,
        precip_gradient=precip_grad,
        phase_method=cfg.downscaling.phase_method,
        t_snow=cfg.downscaling.t_snow_threshold_c + 273.15,
        t_rain=cfg.downscaling.t_rain_threshold_c + 273.15,
        t_air_max=cfg.downscaling.t_air_max_c + 273.15,
        lapse_rate=cfg.downscaling.lapse_rate,
    )

    n_units = len(domain.units) if domain.units is not None else 1
    progress_steps[downscale_step]["status"] = "active"
    progress_steps[downscale_step]["total"] = n_units
    _write_progress(config_dir, progress_steps)

    _last_progress_write = [0.0]
    def _ds_progress_callback(done, total):
        now = time.time()
        if done == total or now - _last_progress_write[0] > 1.0:
            progress_steps[downscale_step]["completed"] = done
            progress_steps[downscale_step]["total"] = total
            _write_progress(config_dir, progress_steps)
            _last_progress_write[0] = now

    ds_time = time.time()
    # ENS member-looping is handled one level up (forecast_run) so each member's
    # full preprocessing+downscale runs on clean 3D data; here forcing is always
    # single-realization.
    results = downscaler.process(
        domain.units, forcing, domain.dem_data,
        requested_outputs=requested_outputs or None,
        progress_callback=_ds_progress_callback,
    )
    ds_elapsed = time.time() - ds_time
    progress_steps[downscale_step]["status"] = "complete"
    progress_steps[downscale_step]["completed"] = n_units
    _write_progress(config_dir, progress_steps)

    console.print(f"  {prefix}Downscaled {len(domain.units)} units in {ds_elapsed:.1f}s")
    console.print(f"  {prefix}Output variables: {list(results.data_vars)}")

    if skip_output:
        return results

    # === Output statistics ===
    console.print("\n[bold]Output Statistics:[/bold]")
    for var in ["temperature", "precipitation", "shortwave_direct", "longwave"]:
        if var in results:
            data = results[var].values
            console.print(f"  {var}: {np.nanmin(data):.1f} to {np.nanmax(data):.1f} (mean={np.nanmean(data):.2f})")

    # === Write output ===
    console.print(f"\n[bold]Write Output ({cfg.output.format})[/bold]")
    update_live_dashboard(config_dir, status="Running", step="Write Output")
    progress_steps[output_step]["status"] = "active"
    _write_progress(config_dir, progress_steps)
    output_dir = Path(cfg.output.directory)
    output_dir.mkdir(parents=True, exist_ok=True)

    if cfg.output.format == "zarr":
        output_path = output_dir / "forcing.zarr"
        for var in results.variables:
            results[var].encoding.pop("chunks", None)
        with_cf_metadata(results).to_zarr(str(output_path), mode="w")
        console.print(f"  Written: {output_path}")
    elif cfg.output.format == "netcdf":
        output_path = output_dir / "forcing.nc"
        with_cf_metadata(results).to_netcdf(str(output_path))
        console.print(f"  Written: {output_path}")
    else:
        console.print(f"  [yellow]Output format '{cfg.output.format}' writer not yet implemented[/yellow]")

    # === Raster output (optional) ===
    if raster_output or geotiff_var:
        from topopyscale2.outputs.raster_mapper import RasterMapper

        console.print("\n[bold]Raster Output[/bold]")
        try:
            mapper = RasterMapper.from_domain(domain)
            if raster_output:
                raster_path = output_dir / "forcing_raster.zarr"
                mapper.write_raster_dataset(results, raster_path, format="zarr")
                console.print(f"  Raster output: {raster_path}")
            if geotiff_var:
                if geotiff_var not in results:
                    console.print(f"  [yellow]Variable '{geotiff_var}' not in output, skipping GeoTIFF.[/yellow]")
                else:
                    geotiff_dir = output_dir / "geotiffs" / geotiff_var
                    paths = mapper.write_geotiff_series(results, geotiff_dir, geotiff_var)
                    console.print(f"  GeoTIFFs: {geotiff_dir}/ ({len(paths)} files)")
        except Exception as e:
            console.print(f"  [yellow]Raster output failed: {e}[/yellow]")

    progress_steps[output_step]["status"] = "complete"
    progress_steps[output_step]["completed"] = 1
    _write_progress(config_dir, progress_steps)

    return results


# =============================================================================
# Forecast Commands
# =============================================================================


@app.command(name="evaluate-clusters")
def evaluate_clusters(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
    elbow: bool = typer.Option(
        False, "--elbow", "-e",
        help="Run elbow analysis across a range of k values."
    ),
    k_min: int = typer.Option(50, "--k-min", help="Minimum k for elbow analysis."),
    k_max: int = typer.Option(5000, "--k-max", help="Maximum k for elbow analysis."),
    k_steps: int = typer.Option(8, "--k-steps", help="Number of k values to test in elbow analysis."),
):
    """Evaluate cluster quality metrics to help choose n_clusters.

    Computes silhouette score, Calinski-Harabasz index, and Davies-Bouldin
    index for the configured clustering. Optionally runs an elbow analysis
    across a range of k values.

    Metrics guide:
    - Silhouette: -1 to 1 (higher = better separated clusters)
    - Calinski-Harabasz: higher = denser, better separated
    - Davies-Bouldin: lower = better separated
    - Inertia: lower = tighter clusters (but always decreases with k)
    """
    import os

    from topopyscale2.config.schema import TPS2Config
    from topopyscale2.domain import Domain

    config = config.resolve()
    os.chdir(config.parent)

    console.print(f"[bold]Cluster Evaluation: {config.name}[/bold]")

    cfg = TPS2Config.from_yaml(config)
    domain = Domain(cfg)

    # Run domain setup (DEM + clustering)
    console.print("\n[bold]Step 1: Domain Setup[/bold]")
    domain.setup()

    if domain.dem_data is not None and "elevation" in domain.dem_data:
        elev = domain.dem_data["elevation"]
        console.print(f"  DEM: {elev.shape[0]}x{elev.shape[1]} pixels")
        console.print(f"  Elevation: {float(elev.min()):.0f} - {float(elev.max()):.0f} m")

    # Evaluate current clustering
    console.print(f"\n[bold]Step 2: Evaluate k={cfg.clustering.n_clusters}[/bold]")
    clustering = domain._clustering
    if clustering is None:
        console.print("[red]Error: No clustering object found. Is spatial_mode set to 'clusters'?[/red]")
        raise typer.Exit(1)

    metrics = clustering.evaluate()
    console.print(f"\n[bold]Cluster Quality Metrics (k={metrics['n_clusters']}):[/bold]")
    console.print(f"  Samples:           {metrics['n_samples']:,}")
    console.print(f"  Silhouette:        {metrics['silhouette']:.4f}  (higher is better, range -1 to 1)")
    console.print(f"  Calinski-Harabasz: {metrics['calinski_harabasz']:.1f}  (higher is better)")
    console.print(f"  Davies-Bouldin:    {metrics['davies_bouldin']:.4f}  (lower is better)")
    console.print(f"  Inertia:           {metrics['inertia']:.1f}")
    if metrics.get("silhouette_sampled"):
        console.print("  (silhouette subsampled to 50k points)")

    # Elbow analysis
    if elbow:
        console.print(f"\n[bold]Step 3: Elbow Analysis (k={k_min} to {k_max}, {k_steps} steps)[/bold]")
        k_values = [int(k) for k in np.linspace(k_min, k_max, k_steps)]
        # Include configured k if not already present
        if cfg.clustering.n_clusters not in k_values:
            k_values.append(cfg.clustering.n_clusters)
            k_values.sort()

        results = clustering.elbow_analysis(domain.dem_data, k_values)

        console.print(f"\n[bold]{'k':>6}  {'Silhouette':>10}  {'Calinski-H':>10}  {'Davies-B':>10}  {'Inertia':>14}[/bold]")
        console.print(f"  {'─'*6}  {'─'*10}  {'─'*10}  {'─'*10}  {'─'*14}")
        for m in results:
            marker = " ◄" if m["n_clusters"] == cfg.clustering.n_clusters else ""
            console.print(
                f"  {m['n_clusters']:>5}  {m['silhouette']:>10.4f}  "
                f"{m['calinski_harabasz']:>10.1f}  {m['davies_bouldin']:>10.4f}  "
                f"{m['inertia']:>14.1f}{marker}"
            )

        # Find best silhouette
        best = max(results, key=lambda m: m["silhouette"])
        console.print(f"\n  Best silhouette: k={best['n_clusters']} ({best['silhouette']:.4f})")

    console.print("\n[green]Evaluation complete.[/green]")


@app.command()
def preflight(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
    strict: bool = typer.Option(
        False, "--strict",
        help="Exit code 1 on any warning (for CI)."
    ),
    skip_disk: bool = typer.Option(
        False, "--skip-disk",
        help="Skip disk space check (useful for network storage)."
    ),
):
    """Run preflight checks on config before starting a simulation.

    Validates configuration parameters, checks backend availability,
    estimates runtime and data volumes, and catches obvious misconfigurations
    before committing to a multi-hour pipeline run.

    Examples:

        tps2 preflight -c config.yaml

        tps2 preflight -c config.yaml --strict

        tps2 preflight -c config.yaml --skip-disk
    """
    from topopyscale2.config.schema import TPS2Config
    from topopyscale2.preflight import run_preflight

    try:
        cfg = TPS2Config.from_yaml(config)
    except Exception as e:
        console.print(f"[red]Config parse error: {e}[/red]")
        raise typer.Exit(1)

    report = run_preflight(cfg, skip_disk=skip_disk)

    # Print with Rich markup for colored icons
    status_styles = {"pass": "green", "warn": "yellow", "fail": "red"}
    status_icons = {"pass": "\u2713", "warn": "\u26a0", "fail": "\u2717"}

    console.print(f"\n[bold]Preflight Checks: {config.name}[/bold]\n")

    # Group checks by category
    categories: dict[str, list] = {}
    for check in report.checks:
        cat = check.category or "General"
        categories.setdefault(cat, []).append(check)

    for cat, checks in categories.items():
        console.print(f"  [bold]{cat}[/bold]")
        for c in checks:
            icon = status_icons[c.status]
            style = status_styles[c.status]
            console.print(f"  [{style}]{icon}[/{style}] {c.message}")
        console.print()

    # Estimates table
    if report.estimates:
        console.print("  [bold]Estimates[/bold]")
        sep = "\u2500"
        console.print(f"  {'Stage':<20} {'Data Volume':<14} {'Est. Time'}")
        console.print(f"  {sep*20} {sep*14} {sep*14}")
        for est in report.estimates:
            console.print(f"  {est.stage:<20} {est.volume_str:<14} {est.time_str}")

        total_vol = f"~{report.total_volume_gb:.1f} GB"
        low, high = report.total_time_low, report.total_time_high
        if low < 1 and high < 1:
            total_time = f"~{high * 60:.0f}s"
        else:
            total_time = f"~{low:.0f}-{high:.0f} min"
        console.print(f"  {sep*20} {sep*14} {sep*14}")
        console.print(f"  {'Total':<20} {total_vol:<14} {total_time}")
        console.print()

    # Summary
    summary = f"  {report.n_pass} passed, {report.n_warn} warning(s), {report.n_fail} error(s)"
    if report.n_fail > 0:
        console.print(f"[red]{summary}[/red]")
    elif report.n_warn > 0:
        console.print(f"[yellow]{summary}[/yellow]")
    else:
        console.print(f"[green]{summary}[/green]")

    if report.n_fail > 0 or (strict and report.n_warn > 0):
        raise typer.Exit(1)


@app.command()
def info(
    config: Path = typer.Option(..., "--config", "-c", help="Path to YAML config file"),
):
    """Show domain summary information including Phase 2 configuration."""
    from topopyscale2.config.schema import TPS2Config

    cfg = TPS2Config.from_yaml(config)

    console.print(f"[bold]Configuration: {config}[/bold]")
    console.print("\n[bold]Domain:[/bold]")
    console.print(f"  Bbox: {cfg.domain.bbox}")
    console.print(f"  DEM source: {cfg.domain.dem_source}")
    console.print(f"  Spatial mode: {cfg.domain.spatial_mode}")
    console.print(f"  CRS: {cfg.domain.crs}")

    if cfg.domain.spatial_mode == "polygons":
        console.print("\n[bold]Polygon Configuration:[/bold]")
        console.print(f"  Method: {cfg.polygons.method}")
        console.print(f"  Elevation bands: {cfg.polygons.elevation_bands}m")
        console.print(f"  Aspect classes: {cfg.polygons.aspect_classes}")
        console.print(f"  Respect catchments: {cfg.polygons.respect_catchments}")
        console.print(f"  Min area: {cfg.polygons.min_area_m2} m2")
    else:
        console.print("\n[bold]Clustering:[/bold]")
        console.print(f"  Method: {cfg.clustering.method}")
        console.print(f"  N clusters: {cfg.clustering.n_clusters}")
        console.print(f"  Features: {cfg.clustering.features}")

    console.print("\n[bold]Inputs:[/bold]")
    console.print(f"  Primary: {cfg.inputs.primary}")
    console.print(f"  Backend: {cfg.inputs.backend}")
    console.print(f"  Time range: {cfg.inputs.time_range}")

    if cfg.inputs.sources:
        console.print(f"  NWP sources: {len(cfg.inputs.sources)}")
        for src in cfg.inputs.sources:
            console.print(f"    - {src.name} ({src.type}, priority {src.priority})")
        console.print(f"  Blending: {cfg.inputs.blending.method if cfg.inputs.blending.enabled else 'disabled'}")

    console.print("\n[bold]Downscaling:[/bold]")
    # What the engine does with this config (not the informational method strings).
    d = cfg.downscaling
    if d.mode == "full":
        levels = ", ".join(str(p) for p in cfg.inputs.pressure_levels)
        console.print(f"  Temperature, humidity: pressure levels ({levels} hPa) at each unit's elevation")
    else:
        console.print(f"  Temperature: surface + fixed lapse rate {d.lapse_rate * 1000:.2f} °C/km")
    console.print("  Radiation: slope, aspect, horizon shading and sky-view correction")
    console.print(f"  Wind: {d.wind_config.method}")
    if d.precipitation == "elevation_gradient":
        console.print(f"  Precipitation: ERA5 amount scaled by {d.precip_gradient * 1e4:.1f} % per 100 m")
    else:
        console.print("  Precipitation: ERA5 amount for every unit (no elevation gradient)")
    console.print(f"  Rain/snow: {d.phase_method}, all snow below {d.t_snow_threshold_c} °C, "
                  f"all rain above {d.t_rain_threshold_c} °C (and above {d.t_air_max_c} °C air)")

    if cfg.downscaling.redistribution.wind_transport or cfg.downscaling.redistribution.avalanche:
        console.print("\n[bold]Redistribution:[/bold]")
        console.print(f"  Wind transport: {cfg.downscaling.redistribution.wind_transport}")
        console.print(f"  Avalanche: {cfg.downscaling.redistribution.avalanche}")
        if cfg.downscaling.redistribution.avalanche:
            console.print(f"  Avalanche threshold: {cfg.downscaling.redistribution.avalanche_slope_threshold} deg")

    console.print("\n[bold]Execution:[/bold]")
    console.print(f"  Backend: {cfg.execution.backend}")
    console.print(f"  Kernel backend: {cfg.execution.kernel_backend}")
    console.print(f"  Workers: {cfg.execution.n_workers}")

    if cfg.execution.backend == "slurm":
        console.print(f"  SLURM partition: {cfg.execution.slurm.partition}")
        console.print(f"  SLURM time: {cfg.execution.slurm.time}")

    console.print("\n[bold]Output:[/bold]")
    console.print(f"  Format: {cfg.output.format}")
    console.print(f"  Directory: {cfg.output.directory}")
    console.print(f"  Variables: {len(cfg.output.variables)} configured")

    console.print("\n[bold]Storage:[/bold]")
    console.print(f"  Cache format: {cfg.storage.input_cache_format}")
    console.print(f"  Working format: {cfg.storage.working_format}")
    console.print(f"  Compression: {cfg.storage.compression}")

    if cfg.application.model != "none":
        console.print("\n[bold]Application:[/bold]")
        console.print(f"  Model: {cfg.application.model}")
        console.print(f"  Feedback: {cfg.application.feedback.method if cfg.application.feedback.enabled else 'disabled'}")
        console.print(f"  State DA: {cfg.application.state_da.method if cfg.application.state_da.enabled else 'disabled'}")


# =============================================================================
# QC Commands
# =============================================================================


# =============================================================================
# Application Layer Commands
# =============================================================================


# =============================================================================
# Dashboard Command
# =============================================================================


# =============================================================================
# Climatology Commands
# =============================================================================


# =============================================================================
# Cache Management Commands
# =============================================================================


@app.command()
def view(
    sim_dir: Path = typer.Argument(..., help="Simulation directory (after `tps2 run`)"),
    output: Optional[Path] = typer.Option(
        None, "--output", "-o", help="HTML file to write (default: <sim_dir>/output/forcing_page.html)"),
    page: Optional[Path] = typer.Option(
        None, "--page", help="YAML with the page's title, text, credits and logo"),
    save_daily: bool = typer.Option(
        False, "--save-daily",
        help="Also write output/forcing_daily.nc, a compact daily summary the page can be rebuilt from"),
):
    """Write a self-contained HTML page of the downscaled forcing.

    One offline file: pick temperature, precipitation, snowfall, shortwave, longwave, wind or
    humidity and watch it through the season on the terrain, against elevation, and at any
    terrain unit.

    Examples:
        tps2 view ~/sim/alps_2023
        tps2 view ~/sim/alps_2023 -o alps.html --page page.yaml
    """
    from topopyscale2.outputs.forcing_page import (
        PageText,
        generate_forcing_page,
        write_daily_summary,
    )

    if save_daily:
        path = write_daily_summary(sim_dir)
        console.print(f"[green]Daily summary:[/green] {path}")
    spec = PageText.from_yaml(page) if page else None
    out = generate_forcing_page(sim_dir, output, page=spec)
    console.print(f"[green]Forcing page:[/green] {out}")


@app.command()
def ui(
    sim_dir: Path = typer.Argument(Path("."), help="Simulation directory to configure and run (created if missing)"),
    port: int = typer.Option(8765, "--port", "-p", help="Port on 127.0.0.1"),
    no_browser: bool = typer.Option(False, "--no-browser", help="Do not open a browser tab"),
):
    """Open a local page to configure a run, start it and view the result.

    Serves on 127.0.0.1 only (it has no login). Stop it with Ctrl+C.

    Examples:
        tps2 ui ~/sim/davos
        tps2 ui ~/sim/davos --port 8800 --no-browser
    """
    import webbrowser

    from topopyscale2.ui.server import make_server

    sim_dir = sim_dir.resolve()
    sim_dir.mkdir(parents=True, exist_ok=True)
    server, _state = make_server(sim_dir, port=port)
    url = f"http://127.0.0.1:{server.server_address[1]}/"
    console.print(f"[green]tps2 ui[/green] for {sim_dir}\n  {url}   (Ctrl+C to stop)")
    if not no_browser:
        webbrowser.open(url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        console.print("stopped")
    finally:
        server.server_close()


@app.command(name="build-cache")
def build_cache(
    output: Path = typer.Argument(..., help="Path to output Zarr store (e.g. ./era5_cache/region.zarr)"),
    bbox: Optional[str] = typer.Option(
        None, "--bbox", "-b",
        help="Bounding box: west,south,east,north (e.g. 60,25,105,50)",
    ),
    time: Optional[str] = typer.Option(
        None, "--time", "-t",
        help="Time range: start,end (e.g. 2000-01-01,2024-12-31)",
    ),
    levels: str = typer.Option(
        "1000,925,850,800,700,600,550,500,400,300",
        "--levels", "-l",
        help="Comma-separated pressure levels in hPa",
    ),
    backend: str = typer.Option(
        "google", "--backend",
        help="Download backend (google, cds, openmeteo)",
    ),
    workers: int = typer.Option(
        4, "--workers", "-w",
        help="Number of parallel download workers",
    ),
    resolution: str = typer.Option(
        "1H", "--resolution", "-r",
        help="Time resolution (1H, 2H, 3H, 6H)",
    ),
    update: bool = typer.Option(
        False, "--update", "-u",
        help="Update existing cache with new dates",
    ),
    info: bool = typer.Option(
        False, "--info",
        help="Print cache metadata and exit",
    ),
    chunk_lat: int = typer.Option(45, "--chunk-lat", help="Latitude chunk size"),
    chunk_lon: int = typer.Option(45, "--chunk-lon", help="Longitude chunk size"),
    no_throttle: bool = typer.Option(
        False, "--no-throttle",
        help="Disable adaptive rate limiting (not recommended for large builds)",
    ),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt"),
):
    """Build a regional ERA5 Zarr cache for fast local access.

    Downloads ERA5 data and consolidates into a single Zarr store with
    optimised regional chunking. Subsequent simulations using backend=local
    read from this cache in seconds instead of re-downloading.

    Examples:

        tps2 build-cache ./era5_cache/region.zarr --bbox 60,25,105,50 --time 2000-01-01,2024-12-31

        tps2 build-cache ./era5_cache/region.zarr --info

        tps2 build-cache ./era5_cache/region.zarr --update
    """
    from rich.table import Table

    from topopyscale2.inputs.nwp_downloader.cache_builder import CacheBuilder

    output = output.resolve()

    # ── Info mode ──────────────────────────────────────────────────────
    if info:
        if not output.exists():
            console.print(f"[red]Cache not found: {output}[/red]")
            raise typer.Exit(1)

        meta = CacheBuilder.info(output)

        table = Table(title=f"Cache: {output}")
        table.add_column("Property", style="bold")
        table.add_column("Value")

        table.add_row("Version", str(meta["cache_version"]))
        table.add_row("Bbox", str(meta["bbox"]))
        table.add_row("Time range", f"{meta['time_range'][0]} to {meta['time_range'][1]}")
        table.add_row("Days", f"{meta['n_days']} / {meta['expected_days']} expected")
        table.add_row("Missing days", str(len(meta["missing_days"])))
        table.add_row("Pressure levels", str(meta["pressure_levels"]))
        table.add_row("Surface vars", ", ".join(meta["surf_vars"]))
        table.add_row("Plev vars", ", ".join(meta["plev_vars"]))
        table.add_row("Time resolution", meta["time_resolution"])
        table.add_row("Chunks", str(meta["chunks"]))
        table.add_row("Size", f"{meta['size_gb']:.2f} GB")

        if meta["missing_days"]:
            n = len(meta["missing_days"])
            sample = meta["missing_days"][:5]
            gaps = ", ".join(sample)
            if n > 5:
                gaps += f" ... (+{n - 5} more)"
            table.add_row("Gap dates", gaps)

        console.print(table)
        raise typer.Exit()

    # ── Update mode ───────────────────────────────────────────────────
    if update:
        if not output.exists():
            console.print(f"[red]Cache not found: {output}[/red]")
            raise typer.Exit(1)

        console.print(f"[bold]Updating cache: {output}[/bold]")
        CacheBuilder.update(
            output,
            backend=backend,
            max_workers=workers,
        )
        console.print("[green]Cache updated.[/green]")
        raise typer.Exit()

    # ── Build mode ────────────────────────────────────────────────────
    if not bbox:
        console.print("[red]--bbox is required for initial build (e.g. --bbox 60,25,105,50)[/red]")
        raise typer.Exit(1)
    if not time:
        console.print("[red]--time is required for initial build (e.g. --time 2000-01-01,2024-12-31)[/red]")
        raise typer.Exit(1)

    # Parse bbox
    try:
        bbox_parts = [float(x.strip()) for x in bbox.split(",")]
        if len(bbox_parts) != 4:
            raise ValueError
        bbox_tuple = tuple(bbox_parts)
    except (ValueError, AttributeError):
        console.print("[red]Invalid bbox format. Use: west,south,east,north[/red]")
        raise typer.Exit(1)

    # Parse time range
    try:
        time_parts = [x.strip() for x in time.split(",")]
        if len(time_parts) != 2:
            raise ValueError
        start_date, end_date = time_parts
    except (ValueError, AttributeError):
        console.print("[red]Invalid time format. Use: start,end (e.g. 2000-01-01,2024-12-31)[/red]")
        raise typer.Exit(1)

    # Parse pressure levels
    pressure_levels = [int(x.strip()) for x in levels.split(",")]

    # Estimate size
    import pandas as pd

    n_days = (pd.Timestamp(end_date) - pd.Timestamp(start_date)).days + 1
    w, s, e, n = bbox_tuple
    n_lat = int(abs(n - s) / 0.25) + 1
    n_lon = int(abs(e - w) / 0.25) + 1
    n_levels = len(pressure_levels)
    hours_per_day = {"1H": 24, "2H": 12, "3H": 8, "6H": 4}.get(resolution, 24)

    # Rough estimate: 15 vars * 4 bytes * time * lat * lon * compression ~0.3x
    bytes_est = 15 * 4 * n_days * hours_per_day * n_lat * n_lon * 0.3
    # Add plev contribution
    bytes_est += 5 * 4 * n_days * hours_per_day * n_lat * n_lon * n_levels * 0.3
    gb_est = bytes_est / (1024**3)

    console.print("[bold]Build ERA5 cache[/bold]")
    console.print(f"  Output:     {output}")
    console.print(f"  Bbox:       {bbox_tuple}")
    console.print(f"  Time:       {start_date} to {end_date} ({n_days} days)")
    console.print(f"  Levels:     {pressure_levels}")
    console.print(f"  Grid:       {n_lat} x {n_lon} (~{n_lat * n_lon} points)")
    console.print(f"  Resolution: {resolution}")
    console.print(f"  Backend:    {backend}")
    console.print(f"  Est. size:  ~{gb_est:.0f} GB")

    if not yes:
        confirm = typer.confirm("Proceed?")
        if not confirm:
            raise typer.Exit()

    chunks = {
        "time": 24,
        "latitude": chunk_lat,
        "longitude": chunk_lon,
        "level": -1,
    }

    backend_kwargs = {}
    if no_throttle:
        backend_kwargs["throttle"] = False

    builder = CacheBuilder(
        backend=backend,
        bbox=bbox_tuple,
        start_date=start_date,
        end_date=end_date,
        pressure_levels=pressure_levels,
        output_path=output,
        chunks=chunks,
        max_workers=workers,
        time_resolution=resolution,
        backend_kwargs=backend_kwargs,
    )
    builder.build()

    console.print(f"[green]Cache built: {output}[/green]")

    # Print summary
    meta = CacheBuilder.info(output)
    console.print(f"  Size: {meta['size_gb']:.2f} GB, {meta['n_days']} days")


# =============================================================================
# Data Assimilation Commands
# =============================================================================


# Commands outside the v1 downscaling core. Each module registers its commands on
# `app` when imported; a release that does not ship a module simply lacks them. Only
# an ABSENT module is skipped: a module that is present but fails to import raises,
# so a broken optional command can never vanish silently.
def _register_optional_commands() -> None:
    import importlib
    import importlib.util

    for name in ("stations_cli", "forecast_cli", "snow_cli", "da_cli"):
        if importlib.util.find_spec(f"topopyscale2.cli.{name}") is not None:
            importlib.import_module(f"topopyscale2.cli.{name}")
    for name, attr, group in (("climate_cli", "climate_app", "climate"),
                              ("topoclim_cli", "topoclim_app", "topoclim"),
                              ("lab_cli", "lab_app", "lab")):
        if importlib.util.find_spec(f"topopyscale2.cli.{name}") is not None:
            app.add_typer(getattr(importlib.import_module(f"topopyscale2.cli.{name}"), attr), name=group)


_register_optional_commands()


# Last, after the optional commands are registered: `python -m topopyscale2.cli.main`
# (how the operational run.sh scripts call TPS2) runs this module as __main__, and would
# otherwise start the app with only the core commands.
if __name__ == "__main__":
    app()
