"""HBV model format output writer."""

from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

from topopyscale2.spatial.units import SpatialUnit


class HBVWriter:
    """Write forcing in HBV daily format.

    HBV (Hydrologiska Byrans Vattenbalansavdelning) is a conceptual
    hydrological model. The input format requires daily aggregated values:
    - Temperature (daily mean) [degrees C]
    - Precipitation (daily sum) [mm]
    - Potential Evapotranspiration (daily) [mm]

    Can output either:
    - One file per unit (multi-column CSV or text)
    - One file per catchment with multiple units (columns)

    Standard column format: Date, T, P, PET
    """

    model_name = "hbv"
    file_format = "txt"

    def __init__(
        self,
        temp_unit: str = "celsius",
        pet_method: str = "hamon",
        date_format: str = "%Y%m%d",
        single_file: bool = False,
    ):
        """Initialize HBV writer.

        Parameters
        ----------
        temp_unit : str
            Temperature unit: "celsius" or "kelvin".
        pet_method : str
            PET estimation method: "hamon", "thornthwaite", or "none".
            If "none", PET column will be filled with zeros.
        date_format : str
            Date format string for output.
        single_file : bool
            If True, write all units to a single file with unit columns.
        """
        self.temp_unit = temp_unit
        self.pet_method = pet_method
        self.date_format = date_format
        self.single_file = single_file

    def _kelvin_to_celsius(self, temp_k: np.ndarray) -> np.ndarray:
        """Convert Kelvin to Celsius."""
        return temp_k - 273.15

    def _compute_hamon_pet(
        self,
        temp_c: np.ndarray,
        dates: pd.DatetimeIndex,
        latitude: float,
    ) -> np.ndarray:
        """Compute daily PET using Hamon method.

        Parameters
        ----------
        temp_c : array
            Daily mean temperature in Celsius.
        dates : DatetimeIndex
            Date values.
        latitude : float
            Latitude in degrees.

        Returns
        -------
        array
            Daily PET in mm.
        """
        # Day of year
        doy = dates.dayofyear.values

        # Daylight hours approximation
        lat_rad = np.radians(latitude)
        declination = 0.409 * np.sin(2.0 * np.pi / 365.0 * doy - 1.39)
        sunset_hour_angle = np.arccos(-np.tan(lat_rad) * np.tan(declination))
        daylight_hours = 24.0 / np.pi * sunset_hour_angle

        # Saturated vapor pressure at temp
        es = 0.6108 * np.exp(17.27 * temp_c / (temp_c + 237.3))

        # Hamon PET (mm/day)
        pet = np.where(
            temp_c > 0,
            0.165 * 216.7 * daylight_hours / 12.0 * es / (temp_c + 273.3),
            0.0,
        )

        return np.maximum(pet, 0.0)

    def _aggregate_to_daily(
        self,
        ds: xr.Dataset,
    ) -> tuple[pd.DatetimeIndex, np.ndarray, np.ndarray]:
        """Aggregate hourly data to daily.

        Parameters
        ----------
        ds : xr.Dataset
            Hourly forcing data.

        Returns
        -------
        dates : DatetimeIndex
            Daily dates.
        temp : array
            Daily mean temperature.
        precip : array
            Daily precipitation sum.
        """
        # Convert to pandas for easy resampling
        temp = ds["temperature"].to_series()
        precip = ds["precipitation"].to_series()

        # Resample to daily
        temp_daily = temp.resample("D").mean()
        precip_daily = precip.resample("D").sum()  # kg m-2 per step = mm; daily total in mm

        dates = pd.DatetimeIndex(temp_daily.index)

        return dates, temp_daily.values, precip_daily.values

    def _write_hbv_file(
        self,
        filepath: Path,
        dates: pd.DatetimeIndex,
        temp: np.ndarray,
        precip: np.ndarray,
        pet: np.ndarray,
    ) -> None:
        """Write a single HBV file.

        Parameters
        ----------
        filepath : Path
            Output file path.
        dates : DatetimeIndex
            Date values.
        temp : array
            Daily mean temperature (Celsius).
        precip : array
            Daily precipitation (mm).
        pet : array
            Daily PET (mm).
        """
        with open(filepath, "w", encoding="utf-8") as f:
            # Header
            f.write("# HBV forcing file generated by TopoPyScale 2.0\n")
            f.write("# Date T[C] P[mm] PET[mm]\n")

            for i, dt in enumerate(dates):
                date_str = dt.strftime(self.date_format)
                f.write(f"{date_str} {temp[i]:.2f} {precip[i]:.3f} {pet[i]:.3f}\n")

    def write(
        self,
        forcing: xr.Dataset,
        units: list[SpatialUnit],
        output_dir: Path,
    ) -> list[Path]:
        """Write HBV forcing files.

        Parameters
        ----------
        forcing : xr.Dataset
            Forcing data with dims (time,) or (time, unit_id).
        units : list[SpatialUnit]
            Spatial units.
        output_dir : Path
            Output directory.

        Returns
        -------
        list[Path]
            Written file paths.
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        written = []

        if self.single_file and len(units) > 1:
            # Write all units to single file
            return self._write_combined(forcing, units, output_dir)

        for i, unit in enumerate(units):
            # Extract data for this unit
            if "unit_id" in forcing.dims:
                ds = forcing.isel(unit_id=i)
            else:
                ds = forcing

            # Aggregate to daily
            dates, temp_daily, precip_daily = self._aggregate_to_daily(ds)

            # Convert temperature
            if self.temp_unit == "celsius":
                temp_daily = self._kelvin_to_celsius(temp_daily)

            # Compute PET
            if self.pet_method == "hamon":
                pet_daily = self._compute_hamon_pet(temp_daily, dates, unit.y)
            elif self.pet_method == "thornthwaite":
                # Simplified Thornthwaite (similar to Hamon for basic use)
                pet_daily = self._compute_hamon_pet(temp_daily, dates, unit.y)
            else:
                pet_daily = np.zeros_like(temp_daily)

            filepath = output_dir / f"hbv_{unit.id}.txt"
            self._write_hbv_file(filepath, dates, temp_daily, precip_daily, pet_daily)
            written.append(filepath)

        return written

    def _write_combined(
        self,
        forcing: xr.Dataset,
        units: list[SpatialUnit],
        output_dir: Path,
    ) -> list[Path]:
        """Write all units to a single combined file.

        Parameters
        ----------
        forcing : xr.Dataset
            Forcing data with dims (time, unit_id).
        units : list[SpatialUnit]
            Spatial units.
        output_dir : Path
            Output directory.

        Returns
        -------
        list[Path]
            Written file path.
        """
        filepath = output_dir / "hbv_forcing.txt"

        # Get dates from first unit
        if "unit_id" in forcing.dims:
            ds0 = forcing.isel(unit_id=0)
        else:
            ds0 = forcing
        dates, _, _ = self._aggregate_to_daily(ds0)

        with open(filepath, "w", encoding="utf-8") as f:
            # Header
            f.write("# HBV forcing file generated by TopoPyScale 2.0\n")
            f.write("# Combined file for multiple units\n")
            header = "Date"
            for unit in units:
                header += f" T_{unit.id} P_{unit.id} PET_{unit.id}"
            f.write(f"# {header}\n")

            # Collect data for all units
            all_data = []
            for i, unit in enumerate(units):
                if "unit_id" in forcing.dims:
                    ds = forcing.isel(unit_id=i)
                else:
                    ds = forcing

                _, temp_daily, precip_daily = self._aggregate_to_daily(ds)

                if self.temp_unit == "celsius":
                    temp_daily = self._kelvin_to_celsius(temp_daily)

                if self.pet_method == "hamon":
                    pet_daily = self._compute_hamon_pet(temp_daily, dates, unit.y)
                else:
                    pet_daily = np.zeros_like(temp_daily)

                all_data.append((temp_daily, precip_daily, pet_daily))

            # Write data rows
            for j, dt in enumerate(dates):
                date_str = dt.strftime(self.date_format)
                row = date_str
                for temp, precip, pet in all_data:
                    row += f" {temp[j]:.2f} {precip[j]:.3f} {pet[j]:.3f}"
                f.write(row + "\n")

        return [filepath]
